app.swagger:
    path: /api/v1/doc/{area}.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
    path: /api/v1/doc/{area}
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }